### ISSUE TITLE
手机网页端使用有问题

### ISSUE THREAD

**Issue by shenxw0127** [may-today/screen#1]
屏幕模式没有Id
遥控器模式一直转圈输不了数字
![image](https://github.com/may-today/mayday.blue/assets/115412787/88428d49-d203-4710-8fc8-d921135defc5)

**Comment by ddiu8081** [comment]
在PC浏览器上可以正常打开屏幕模式吗？
如果不可以的话，打开浏览器的控制台（右键-检查 或 Ctrl + Shift + J / Cmd + Option + J）,复制其中的信息，谢谢

**Comment by ddiu8081** [comment]
最近发现有类似的反馈，经复现应该是安卓端部分浏览器不支持。

已经加上了一个错误提示窗，如果浏览器不支持的情况下会弹窗提示，可以再看看
